# Being Infected by the Curiosity of Others

> I'll work hard I'll do my part;  You won't hear me complain;  I'll never go down easy; I swear I'll pull my weight. (Sawyer Brown)[^SawyerBrown]

[^SawyerBrown]: From _The Nebraska Song_ by [Sawyer Brown](https://sawyerbrown.com/).  As I am sure my Department Head and others will attest, I am still working on the "not complaining" part!

I attended graduate school intent on entering industry; the primary reason I did not initially consider academia was my aversion to "research."  In general, I have struggled to find the drive required to plan and execute an agenda from idea through publication.  Two examples illustrate this.  Suppose we are interested in determining which characteristics recorded in a patient's medical chart (potential predictors) are associated with experiencing a heart attack (the response); however, we might only have the patient's family history for a subset of the study participants.  Separating the characteristics associated with a response from those that are not is a process known as variable selection; and, as described in our example, we might be interested in doing this in the presence of missing data.  For a number of years, I have nursed an idea of a general approach to this problem that merges techniques developed concurrently in separate areas of statistics.  Several years ago, I even advised a senior capstone (Cody Roberts, 2015) in this area with promising results.  However, I have not pursued the project, continuing instead to prioritize revisions to class materials or the development of new courses (or really any other work).  During the 2022-2023 academic year, upon advice from a colleague, I reviewed the literature on how alternative grading can improve equity in the classroom.  A student (Clara Place, expected 2025) helped me conduct a survey to better understand the experiences of historically underrepresented students with alternative grading at Rose-Hulman.  I completed the paper, but it was rejected from the target journal; and, it has just sat since, me prioritizing day-to-day work.

While I have not developed a research agenda, I have remained active.  We should expect faculty to continue to grow intellectually; for me, this growth is fueled by the curiosity of others.  The most appealing aspect of Statistics for me has always been the ability to collaborate with researchers across a variety of disciplines.  As an applied statistician, my passion is joining such collaborations, particularly in the biological sciences.  The development of an appropriate analysis plan, the implementation of the analysis, and the communication of the results, all in the service of advancing the research being led by others is where I perform best. These opportunities invigorate me, enrich my classroom, have meaningful impacts, and contribute to my growth as a scholar.

:::{.callout-important}
## My Professional Mission as a Collaborator
To _collaborate_ with researchers who want to make a difference.
:::

:::{.callout-note}
As I am both a statistician and a professor, and my collaborations over the years have resulted in growth in both realms.
:::

I am a huge proponent of alternative grading strategies[^website] and could talk about them for hours[^discussions].  Over the past several years, I have engaged in several opportunities to share my experience with others.  This has included two workshops for Rose-Hulman faculty (the first co-led with John Mirth, the second co-led with Sylvia Carlisle), two invited contributions to the [Statistics Teaching and Learning Corner](https://stattlc.com/2021/02/04/specifications-grading-an-overview/), a conference presentation with several Rose-Hulman colleagues (Emma Dosmar, Julia Williams, Rich House, and Sylvia Carlisle), and a wonderful collaboration with educators from several universities (Brenna Curley of Moravian University, Jillian Downey of Gustavus Adolphus College, Katherine M. Kinnaird of U.S. Air Force Academy and Smith College, and Adam Loy of Carleton College).  This latest collaboration has resulted in a publication in the [_Journal for Statistics and Data Science Education_](https://www.tandfonline.com/doi/full/10.1080/26939169.2023.2277851) and a workshop at the [US Conference on Teaching Statistics](https://www.causeweb.org/cause/uscots/uscots23/w14-communicating-progress-statistics-course-through-non-traditional-grading-room).  

[^website]: I have documented several of my experiences on my [personal site](https://reyesem.github.io/specsgrading.html) in hopes of benefiting others.  

[^discussions]: On a recent road trip, my wife, an adjunct in our department, and I spent 8+ hours talking about grading!

Through each of these experiences, the colleagues I have worked with have helped me refine my approach to grading.  In fact, the regular meetings with my latest collaborators have become a high point in my schedule, providing a source of energy for tackling the difficult parts of teaching.  These conversations have been so fruitful and so cathartic to each of us that our latest venture is launching a podcast for educators where we "talk through teaching tensions together" in an effort to share the various experiences educators have in tackling daily challenges in education like navigating the use of technology in the classroom.  It was a great joy to see our hard work recognized in the acceptance of our paper; but, the greater joy (being the "senior" member of the group) was watching all four of my colleagues receive positive tenure decisions following its acceptance.

In addition to my position at Rose-Hulman, I hold the position of Adjunct Clinical Assistant Professor of Biostatistics & Health Data Science through Indiana University.  This position supports my work with the Terre Haute branch of the Indiana University School of Medicine, which houses the [rural health scholarly concentration](https://medicine.iu.edu/md/curriculum/scholarly-concentrations/rural-health).  Through this curriculum, medical students interested in practicing in rural areas gain valuable research skills by leading a research project in the Terre Haute community.  The final deliverable for the project is a manuscript suitable for submission to a journal targeting rural medicine, and it provides an excellent topic of conversation during the students' interviews for residency.

The majority of projects conducted by medical students in this curriculum depend on surveying members of the community.  Given the often limited statistical background of the medical students, the directors of the program (Robin Danek and Ellen Ireland) invited me to collaborate on these projects.  My role on the team is to provide statistical expertise during the design of the survey, the development of an analysis plan, and in reporting the data.  As a true collaborator, I am involved from the early stages of the project review.  Through these projects, I have learned a lot about the challenges facing rural communities in regards to access to healthcare.  I brought this experience back to Rose-Hulman when Jessica Livingston and I developed the [Social Justice and Statistical Concepts course](https://www.rose-hulman.edu/news/2023/interdisciplinary-course-bridges-data-science-and-storytelling.html).  Being a part of the survey development and data analysis also provides rich contexts for the Biostatistics course.  Specifically, my email exchanges with medical students have inspired a set of assignments asking students to use the course material to explain to medical students (in a language they will understand) why more complex analyses (than those learned in an introductory course) are needed to address their question of interest.  Students often find these to be the most challenging assignments of the course.  As they are led by medical students, these collaborations do not always result in publication; the project may end with their presentation to their peers.  Small sample sizes often limit our analyses to graphical summaries; as we allow the medical students to take the lead when possible, this often means guiding them through choosing an appropriate way to summarize their data and the selection of appropriate software.  However, other projects have been very successful, and these typically require more advanced analyses, beyond the capabilities of the student.  In such cases, my role is to determine an analysis that addresses the primary research question and explain it and the results in a such a way that the medical student feels confident explaining it in their interviews.

In addition to working with the medical students, Robin and I have also collaborated on a paper investigating the impact of gender on the differences in mental health treatment between patients in rural and urban communities.  We are currently working on revisions for inclusion in the [_Community Mental Health Journal_](https://link.springer.com/journal/10597); however, this project has already been beneficial to me.  Through the project, I gained familiarity with the [National Survey on Drug Use and Health](https://www.samhsa.gov/data/data-we-collect/nsduh-national-survey-drug-use-and-health); this survey formed the basis of a senior capstone experience for a Biomathematics student, and it should make an excellent source for exploring questions in future senior capstones as well.

:::{.callout-tip}
## Operating as Part of a Team
While I continue to struggle with the false imagery of a researcher as a lone wolf, I have learned that I work best when I am a member of a team, inspired by the natural curiosity of my colleagues.
:::